# Generated by Django 5.0.6 on 2024-05-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rastrobotDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esp32data',
            name='created_at',
        ),
    ]
