# Generated by Django 5.0.6 on 2024-05-31 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastrobotDjango', '0006_rename_sensordireito_esp32data_sensor_direito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32data',
            name='distancia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='esp32data',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='esp32data',
            name='velocidade',
            field=models.FloatField(default=0.0),
        ),
    ]
