# Generated by Django 5.0.6 on 2024-06-07 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('tempo_total', models.FloatField(blank=True, null=True)),
                ('trajeto_total', models.FloatField(blank=True, null=True)),
                ('consumo_medio', models.FloatField(blank=True, null=True)),
                ('aceleracao_media', models.FloatField(blank=True, null=True)),
                ('velocidade_media', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_coleta', models.DateTimeField(auto_now_add=True)),
                ('distancia', models.FloatField()),
                ('velocidade', models.FloatField()),
                ('aceleracao', models.FloatField()),
                ('consumo', models.FloatField()),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrida.corrida')),
            ],
        ),
    ]
